# 参考： https://note.com/tico0602/n/nb2ea4f0b51f8
version: '3'

services:
   web:
       build: .
       command: python3 manage.py runserver 0.0.0.0:8000
       volumes:
           - .:/tmp
       ports:
           - "8000:8000"
       tty: true
       depends_on:
           - db
   db:
       image: postgres:10
       ports:
           - "5432"
       environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres